### ISSUE TITLE
Pull together puzzles take a few seconds to trigger when pulled together

### ISSUE THREAD

**Issue by lummieb** [setrapp/Bond-O-Friendship_Production#11]
Pull together puzzles take a few seconds to trigger when pulled together. They should trigger immediately so that the players know that they have solved the puzzle. A sensitivity problem?

**Comment by setrapp** [comment]
Yes this is a sensitivity problem. In the worst case player can 'solve' the puzzle enough to let the streams flow without actually getting the pushables in the correct place, allowing the islands to move back away from the mainland!

**Comment by setrapp** [comment]
Fixed it. Both join together pieces and zipper pad elements have an exposed field called 'Required Progress' which determines when the piece will consider itself solved. When all pieces are 'solved' they will all jump into their goal positions, completing the puzzle. A value of 1 requires full completion to trigger, while 0 will solve even at furthest bounds. By default they both are set to values near 1 to minimize jump but still solve intuitively.
